<?php
    $title = "Casa da Dona Olivia";
    $desenvolvedor = "Welson Alinor de Barros";

    $tutoriais = array(
        0 => array('id'=>'1', 
            'titulo'=>'Hamburguer na Brasa', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Hamburguer na Brasa (Arroz, Feijão, Hamburguer, Batata Frita, Legumes e Salada). Pequena R$ 16,00. Media R$ 20,00. Grande R$ 22,00.',
            'imagem'=>'img/ma1.jpg', 
            'title_img'=>'Marmitex de Hamburguer na Brasa'),
        1 => array('id'=>'2', 
            'titulo'=>'Costela Assada Com Linguiça', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Costela Assada Com Linguiça  (Arroz Temperado, Feijão, Costela, Linguiça e Salada). Pequena R$ 19,00. Media R$ 22,00. Grande R$ 25,00.',
            'imagem'=>'img/ma2.jpg', 
            'title_img'=>'Marmitex de Costela Assada Com Linguiça'),
        2 => array('id'=>'3', 
            'titulo'=>'Asa de Frango Frito', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Asa de Frango Frito (Arroz, Feijão, Frango Frito, Pure, Legumes e Salada). Pequena R$ 19,00. Media R$ 23,00. Grande R$ 25,00.',
            'imagem'=>'img/ma3.jpg', 
            'title_img'=>'Marmitex de Asa de Frango Frito'),
        3 => array('id'=>'4', 
            'titulo'=>'Bisteca Assada', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Bisteca Assada (Arroz, Feijão, Bisteca Assada, Batata Frita, Legumes e Salada). Pequena R$ 19,00. Media R$ 23,00. Grande R$ 25,00.',                    
            'imagem'=>'img/ma4.jpg', 
            'title_img'=>'Marmitex de Bisteca Assada'),
        4 => array('id'=>'5', 
            'titulo'=>'Cupim Fatiado ', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Cupim Fatiado (Arroz, Feijão, Cupim Fatiado, Batata Frita e Salada). Pequena R$ 18,00. Media R$ 24,00. Grande R$ 27,00.',            
            'imagem'=>'img/ma5.jpg', 
            'title_img'=>'Marmitex de Cupim Fatiado'),
        5 => array('id'=>'6', 
            'titulo'=>'Alcatra Com Batata Frita', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Bife de Alcatra Com Batata Frita (Arroz, Feijão, Bife de Alcatra, Batata Frita, Pure, Legumes e Salada). Pequena R$ 18,00. Media R$ 22,00. Grande R$ 26,00.',
            'imagem'=>'img/ma6.jpg', 
            'title_img'=>'Marmitex de Alcatra Com Batata Frita'),
        6 => array('id'=>'7', 
            'titulo'=>'Coxa de Frango Assada', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Coxa de Frango Assada (Arroz, Feijão, Coxa de Frango Assada, Batata Frita, Legumes e Salada) Pequena R$ 17,00. Media R$ 21,00. Grande R$ 25,00.',
            'imagem'=>'img/ma7.jpg', 
            'title_img'=>'Marmitex de Coxa de Frango Assada'),
        7 => array('id'=>'8', 
            'titulo'=>'Picanha Com Legumes', 
            'autor'=>'Welson A. Barros', 
            'data'=>'2022-08-10', 
            'descricao'=>'Marmitex de Picanha Com Legumes (Arroz, Feijão, Picanha, Batata Frita, Legumes e Salada) Pequena R$ 22,00. Media R$ 26,00. Grande R$ 30,00.',
            'imagem'=>'img/ma8.jpg', 
            'title_img'=>'Marmitex de Picanha Com Legumes'),
             
    );
    
    